  version: 2
  updates:
    # Check for updates to GitHub Actions every week
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
    # Check for Go dependencies with known vulnerabilities every week
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
        interval: "weekly"
