name: merged-to-master
on:
  push:
    branches:
      - main
jobs:
  platform-tools-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag for grpc module
        id: tag_common
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_prefix: common/v
          pre_release_branches: ""
          dry_run: true

      - name: Bump version and push tag for grpc module
        id: tag_grpc
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_prefix: grpc/v
          pre_release_branches: ""
          dry_run: true