name: merged-to-master
on:
  push:
    branches:
      - main
      - "@mzhakun/update-tagging"
jobs:
  tag-common-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check for common module changes
        id: check_common
        run: |
          # Get the latest tag for common module
          LATEST_TAG=$(git tag -l "common/v*" | sort -V | tail -n 1)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "No previous tags for common module"
          else
            # Check if there are changes since the last tag
            CHANGES=$(git diff --name-only $LATEST_TAG HEAD -- common/)
            if [ -n "$CHANGES" ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
              echo "Changes detected in common module since $LATEST_TAG"
            else
              echo "changed=false" >> $GITHUB_OUTPUT
              echo "No changes in common module"
            fi
          fi

      - name: Bump version and create tag for common
        if: steps.check_common.outputs.changed == 'true'
        id: tag_common
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_prefix: common/v
          # Only consider tags for this module when determining version
          custom_tag: common/v

  tag-grpc-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check for grpc module changes
        id: check_grpc
        run: |
          # Get the latest tag for grpc module
          LATEST_TAG=$(git tag -l "grpc/v*" | sort -V | tail -n 1)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "No previous tags for grpc module"
          else
            # Check if there are changes since the last tag
            CHANGES=$(git diff --name-only $LATEST_TAG HEAD -- grpc/)
            if [ -n "$CHANGES" ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
              echo "Changes detected in grpc module since $LATEST_TAG"
            else
              echo "changed=false" >> $GITHUB_OUTPUT
              echo "No changes in grpc module"
            fi
          fi

      - name: Bump version and create tag for grpc
        if: steps.check_grpc.outputs.changed == 'true'
        id: tag_grpc
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_prefix: grpc/v
          # Only consider tags for this module when determining version
          custom_tag: grpc/v