name: CI
env:
  go-version: "1.23"

on:
  pull_request:
    branches:
      - main

jobs:
  platform-tools-ci:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: rainbow-me/github-setup-go-action@v2
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          cache-key: test

      - name: Install tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check tidiness
        run: make tidy

      - name: Run Linters
        run: make lint

      - name: Run Tests
        run: make test

      - name: Check for Vulnerabilities
        run: make govulncheck