name: CI
env:
  go-version: "1.23"

on:
  pull_request:
    branches:
      - main

jobs:
  platform-tools-ci:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
          check-latest: true

      - name: Install tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Linters
        run: make lint

      - name: Run Tests
        run: make test

      - name: Check for Vulnerabilities
        run: make govulncheck