#name: CI test
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches: [main]
#
#concurrency: # cancel in-progress actions upon new branch push on the same PR, to avoid wasting compute time
#  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out source code
#        uses: actions/checkout@v4
#
#      - name: Setup Go
#        uses: ./.github/actions/setup-go-with-cache
#        with:
#          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          cache-key: test
#
#      - name: Check go.mod tidiness
#        run: |
#          make tidy
#
#      - name: Tests
#        run: |
#          make test
