name: CI
env:
  go-version: "1.23"

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true

      - name: install
        run: |
          git config --global url.https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/
          make install
      - name: lint
        run: |
          make lint
      - name: tests
        run: |
          make tests
      - name: Check for vulnerabilities
        run: |
          make govulncheck
